server:
  port: 8089

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/file-upload?serverTimezone=Asia/Seoul
    username: sbsst
    password: sbs123414
  jpa:
    hibernate:
      ddl-auto: create

cloud:
  aws:
    credentials:
      accessKey: AKIAXVDA3VFKPYJVCMZQ
      secretKey: 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
    s3:
      bucket: file-upload-exam
      dir: /
    region:
      static: ap-northeast-2
    stack:
      auto: false
